spring:
  datasource:
    url: jdbc:mysql://localhost/orlp?useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
#server:
#  port: 8088
