spring:
  datasource:
    url: jdbc:mysql://localhost/orlp?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  social:
    google:
      client-id: 109414995516-fftdn22fnpfdh80fgfsvpq1ht97hdkl5.apps.googleusercontent.com
      client-secret: QyK5tYKCYN9KF40Lv--CWfY7
      path: api/auth/google


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh